spring:
    datasource:
        username: root
        password: root12345
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/JdbcManagerSecurity
    jpa:
        show-sql: true
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          ddl-auto: 'create-drop'



