spring:
    datasource:
        username: root
        password: root12345
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/JdbcManagerSecurity-Type-3
    jpa:
        show-sql: true
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          ddl-auto: update
logging:
    pattern.dateformat: yyyy-MM-dd HH:mm:ss.SSS,Europe/Minsk
    level:
        root: INFO
        org.springframework.data.convert.CustomConversions: ERROR

security:
    basic:
        enabled: false
management:
    security:
        enabled: false





